export const MODEL_AR_NAMES: Record<string, string> = {
  ARIMA: "التوقع الإحصائي",
  Prophet: "التوقع الموسمي",
  LSTM: "التوقع الذكي",
  Ensemble: "التوقع المدمج",
};

export const ar = {
  nav: {
    home: "الرئيسية",
    dashboard: "لوحة التحكم",
    news: "الأخبار",
    trends: "اتجاهات السوق",
    seasonal: "التحليل الموسمي",
    aiInsights: "رؤى الذكاء الاصطناعي",
    scraping: "إدارة المصادر",
  },
  common: {
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "إعادة المحاولة",
    noData: "لا توجد بيانات",
    noMarketData: "لا توجد بيانات سوق كافية بعد",
    awaitingFirstCollection: "بانتظار أول دورة جمع بيانات",
    save: "حفظ",
    cancel: "إلغاء",
    refresh: "تحديث",
    delete: "حذف",
    edit: "تعديل",
    search: "بحث",
    export: "تصدير",
    filter: "تصفية",
    close: "إغلاق",
    submit: "إرسال",
    success: "ناجح",
    errorOccurred: "حدث خطأ أثناء العملية",
    active: "نشط",
    inactive: "متوقف",
    warning: "تنبيه",
  },
  dashboard: {
    title: "لوحة التحكم",
    subtitle: "نظرة عامة على مؤشرات سوق الدواجن — البيض المخصب والكتاكيت والأعلاف",
    whiteChick: "كتكوت أبيض",
    sassoChick: "كتكوت ساسو",
    baladiChick: "كتكوت بلدي",
    fertilizedEgg: "بيض مخصب",
    feedIndex: "مؤشر الأعلاف",
    todayNews: "أخبار السوق اليوم",
    noEggData: "لا توجد بيانات بيض مخصب بعد",
    weeklyTrend: "اتجاه الأسعار الأسبوعي",
    eggTrend: "البيض المخصب",
    chickTrend: "الكتاكيت",
    latestPrices: "آخر الأسعار",
    recentTrend: "مؤشرات سريعة",
    aiPoweredInsights: "رؤى ذكاء السوق",
    changeFromLastWeek: "عن الأسبوع الماضي",
    marketOverview: "نظرة السوق",
    fertilizedEggs: "البيض المخصب",
    dayOldChicks: "كتاكيت عمر يوم",
    eggPrices: "أسعار البيض",
    chickPrices: "أسعار الكتاكيت",
  },
  seasonal: {
    title: "التحليل الموسمي",
    subtitle: "تأثير المواسم والمناسبات على أسعار البيض المخصب والكتاكيت والأعلاف",
    event: "المناسبة",
    type: "النوع",
    impact: "التأثير",
    impactPercentage: "نسبة التأثير",
    effectOnPrices: "التأثير على الأسعار",
    monthlyAverages: "متوسط الأسعار الشهرية",
    seasonalSummary: "ملخص موسمي",
    ramadan: "شهر رمضان",
    eidFitr: "عيد الفطر",
    eidAdha: "عيد الأضحى",
    shamNessim: "شم النسيم",
    winter: "الشتاء",
    holyWeek: "أسبوع الآلام",
    christmas: "عيد الميلاد",
    schoolReturn: "عودة المدارس",
  },
  aiInsights: {
    title: "رؤى الذكاء الاصطناعي",
    subtitle: "تحليلات متقدمة ونماذج تنبؤية لسوق الدواجن — البيض المخصب والكتاكيت والأعلاف",
    confidence: "مستوى الثقة",
    modelVersion: "إصدار النموذج",
    lastUpdated: "آخر تحديث",
    modelMetrics: "أداء النماذج",
    dataSources: "مصادر البيانات",
    accuracy: "الدقة",
    mape: "متوسط الخطأ المطلق",
    mae: "متوسط الخطأ المطلق",
    rmse: "جذر متوسط مربع الخطأ",
    modelName: "نموذج التوقع",
    trained: "مدرب",
    notTrained: "غير مدرب",
    readyToTrain: "جاهز للتدريب",
    notAvailable: "غير متاح بعد",
    requires: "يتطلب",
    daysAvailable: "يوم بيانات متاح",
    daysRequired: "يوم بيانات",
    dataSummary: "ملخص البيانات",
    totalDays: "إجمالي الأيام",
    trainedModels: "النماذج المدربة",
    arima: "التوقع الإحصائي",
    prophet: "التوقع الموسمي",
    lstm: "التوقع الذكي",
    ensemble: "التوقع المدمج",
    earlyInsights: "رؤى أولية",
    shortTerm: "اتجاه قصير المدى",
    earlyInsightDesc: "رؤى أولية بناءً على البيانات المتاحة",
    days3: "3 أيام — رؤى أولية",
    days7: "7 أيام — اتجاه قصير المدى",
    days30: "30 يوم — التوقع الإحصائي",
    days45: "45 يوم — التوقع الموسمي",
    days90: "90 يوم — التوقع الذكي",
  },
  trends: {
    title: "اتجاهات السوق",
    subtitle: "تحليل اتجاهات أسعار الكتاكيت والبيض المخصب والأعلاف",
    regionComparison: "مقارنة المحافظات",
    priceHistory: "تاريخ الأسعار",
    yearOverYear: "مقارنة سنوية",
    growthRate: "معدل النمو السنوي",
    volatility: "التذبذب",
    peakMonth: "شهر القمة",
    chickTrend: "اتجاه أسعار الكتاكيت",
    eggTrend: "اتجاه البيض المخصب",
    feedTrend: "اتجاه الأعلاف",
    newsImpact: "تأثير الأخبار على السوق",
  },
  dailyPrices: {
    title: "الأسعار اليومية",
    subtitle: "آخر أسعار البيض المخصب وكتاكيت عمر يوم",
    addPrice: "إضافة سعر جديد",
    priceTable: "جدول الأسعار",
    productType: "نوع المنتج",
    governorate: "المحافظة",
    breed: "السلالة",
    date: "التاريخ",
    price: "السعر",
    unit: "الوحدة",
    category: "التصنيف",
    actions: "الإجراءات",
    pricePerUnit: "السعر للوحدة",
    filters: "التصفية",
    averagePrice: "متوسط السعر",
    allGovernorates: "جميع المحافظات",
    allProducts: "جميع المنتجات",
  },
  predictions: {
    title: "التوقعات",
    subtitle: "توقعات مدعومة بالذكاء الاصطناعي",
    forecast: "التوقع",
    confidence: "مستوى الثقة",
    next30Days: "التوقعات لـ 30 يوماً",
    pricePrediction: "توقع السعر",
    confidenceInterval: "نطاق الثقة",
    modelPerformance: "أداء النموذج",
    upcomingEvents: "الأحداث المتوقعة",
    marketCatalysts: "محفزات السوق",
  },
  form: {
    selectProduct: "اختر نوع المنتج",
    selectGovernorate: "اختر المحافظة",
    selectBreed: "اختر السلالة",
    selectDate: "اختر التاريخ",
    enterPrice: "أدخل السعر",
    priceRequired: "السعر مطلوب",
    priceMustBePositive: "يجب أن يكون السعر أكبر من صفر",
    dateRequired: "التاريخ مطلوب",
    productRequired: "نوع المنتج مطلوب",
    governorateRequired: "المحافظة مطلوبة",
    breedRequired: "السلالة مطلوبة",
    recordAdded: "تم إضافة السجل بنجاح",
    recordDeleted: "تم حذف السجل بنجاح",
    recordUpdated: "تم تحديث السجل بنجاح",
    confirmDelete: "هل أنت متأكد من حذف هذا السجل؟",
  },
  indicators: {
    trendingUp: "اتجاه صاعد",
    trendingDown: "اتجاه هابط",
    stable: "مستقر",
    highConfidence: "ثقة عالية",
    mediumConfidence: "ثقة متوسطة",
    lowConfidence: "ثقة منخفضة",
    positive: "إيجابي",
    negative: "سلبي",
    neutral: "محايد",
  },
};

export type Ar = typeof ar;
